// <auto-generated />
using System;
using AppLivros.API.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AppLivros.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210815200100_PopulaLivro")]
    partial class PopulaLivro
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AppLivros.API.Models.Autor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("Nascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("UltimoNome")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("Autores");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1f179997-38a7-4552-b194-329fcec43882"),
                            Email = "rafa@gmail.com",
                            Nascimento = new DateTime(2008, 5, 1, 8, 30, 52, 0, DateTimeKind.Unspecified),
                            Nome = "Rafael",
                            UltimoNome = "Silva"
                        },
                        new
                        {
                            Id = new Guid("ee55c791-f53e-441e-bea5-7633cc6fbb3f"),
                            Email = "rafa@gmail.com",
                            Nascimento = new DateTime(2008, 5, 1, 8, 30, 52, 0, DateTimeKind.Unspecified),
                            Nome = "Rafaaa",
                            UltimoNome = "Silva"
                        },
                        new
                        {
                            Id = new Guid("c8d9f4f3-a74e-44f7-b479-ce86ae278333"),
                            Email = "rafa@gmail.com",
                            Nascimento = new DateTime(2008, 5, 1, 8, 30, 52, 0, DateTimeKind.Unspecified),
                            Nome = "Leafar",
                            UltimoNome = "Silva"
                        });
                });

            modelBuilder.Entity("AppLivros.API.Models.Livro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Ano")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Livros");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e0f9f132-ad8a-412c-89ae-f7a06d97fd54"),
                            Ano = 2000,
                            ISBN = "8535902775",
                            Titulo = "C# é legal"
                        },
                        new
                        {
                            Id = new Guid("f8aa97a9-a772-4d00-bd8c-758b8666b515"),
                            Ano = 1997,
                            ISBN = "8535902775",
                            Titulo = ".NET é legal"
                        },
                        new
                        {
                            Id = new Guid("13750380-3d1d-4118-914d-702bb3571b5e"),
                            Ano = 1998,
                            ISBN = "8535902775",
                            Titulo = "SQL Server é legal"
                        });
                });

            modelBuilder.Entity("AutorLivro", b =>
                {
                    b.Property<Guid>("AutorsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LivrosId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AutorsId", "LivrosId");

                    b.HasIndex("LivrosId");

                    b.ToTable("AutorLivro");
                });

            modelBuilder.Entity("AutorLivro", b =>
                {
                    b.HasOne("AppLivros.API.Models.Autor", null)
                        .WithMany()
                        .HasForeignKey("AutorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppLivros.API.Models.Livro", null)
                        .WithMany()
                        .HasForeignKey("LivrosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
